apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: petclinic
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/my-cluster/apps/petclinic
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
