apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: petclinic
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/my-cluster/apps/petclinic
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
