apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: petclinic
  namespace: flux-system
spec:
  interval: 5m
  resources:
    - ./helmrelease.yaml         # Reference the HelmRelease file directly
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
