apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: petclinic-dev
  namespace: myapp
spec:
  interval: 10m0s
  path: ./app
  prune: true
  sourceRef:
    kind: GitRepository
    name: petclinic-dev
